### ISSUE TITLE
Newest version from git with Audi e-tron (Q4 50)

### ISSUE THREAD

**Issue by frankjoke** [TA2k/ioBroker.vw-connect#206]
Since about 2 weeks I coulöd not get data for my Q4 e-tron anymore, the adapter could not login to the services.

I have seen on Git that some work have been don in main.js for e-tron key and assumed that this will resolve my problem.

After installation I get now other problems, the login seems to work now because the status gets green for a sort time but afterwards it produces the following errors and gets red again:

```
<html>
<body>
<!--StartFragment-->

vw-connect.0 | 2022-06-21 21:21:11.980 | error | The state contains the forbidden properties batteryStatus, chargingStatus, chargingSettings, chargeMode, plugStatus, climatisationStatus, climatisationSettings, climatisationTimer, windowHeatingStatus, rangeStatus, capabilityStatus, readinessStatus!
-- | -- | -- | --
vw-connect.0 | 2022-06-21 21:21:11.979 | error | Error: The state contains the forbidden properties batteryStatus, chargingStatus, chargingSettings, chargeMode, plugStatus, climatisationStatus, climatisationSettings, climatisationTimer, windowHeatingStatus, rangeStatus, capabilityStatus, readinessStatus! at validateSetStateObjectArgument (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5669:23) at VwWeconnect.setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5752:21) at /opt/iobroker/node_modules/iobroker.vw-connect/main.js:2356:42 at runNextTicks (internal/process/task_queues.js:60:5) at processImmediate (internal/timers.js:437:9)
vw-connect.0 | 2022-06-21 21:21:11.975 | error | unhandled promise rejection: The state contains the forbidden properties batteryStatus, chargingStatus, chargingSettings, chargeMode, plugStatus, climatisationStatus, climatisationSettings, climatisationTimer, windowHeatingStatus, rangeStatus, capabilityStatus, readinessStatus!
vw-connect.0 | 2022-06-21 21:21:11.974 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

<!--EndFragment-->
</body>
</html>```

**Comment by TA2k** [comment]
The raw Json had an issue please reinstall via github and test again
