### ISSUE TITLE
Adapter fails after start-up

### ISSUE THREAD

**Issue by kegelmeier** [TA2k/ioBroker.vw-connect#33]
**Describe the bug**  
Adapter fails after start-up. Data is retrieved but adapter still fails. Loop of restarts follows.

**To Reproduce**  
1. Install Adapter from GitHub
2. LogIn with ID Credentials
3. Go to Logs

**Versions:**  
 - Adapter version: GitHub 18.01.2020
 - Node version: v14.15.4

**Additional context**  
Logs:

2021-01-18 08:18:00.153 - error: host.XX Caught by controller[3]: at extractKeys (/opt/iobroker/node_modules/iobroker.vw-connect/lib/extractKeys.js:27:20)
2021-01-18 08:18:00.154 - error: host.XX Caught by controller[3]: at /opt/iobroker/node_modules/iobroker.vw-connect/lib/extractKeys.js:35:17
2021-01-18 08:18:00.155 - error: host.XX Caught by controller[3]: at Array.forEach ()
2021-01-18 08:18:00.155 - error: host.XX Caught by controller[3]: at VwWeconnect.extractKeys (/opt/iobroker/node_modules/iobroker.vw-connect/lib/extractKeys.js:27:20)
2021-01-18 08:18:00.156 - error: host.XX Caught by controller[3]: at Request._callback (/opt/iobroker/node_modules/iobroker.vw-connect/main.js:1416:30)

**Comment by TA2k** [comment]
Please test with v25

**Comment by kegelmeier** [comment]
Works fine, thanks!
