### ISSUE TITLE
Adapter Funktioniert für ID nicht mehr

### ISSUE THREAD

**Issue by TobiasSt78** [TA2k/ioBroker.vw-connect#74]
Hallo, 

seit 1-2 Tagen funktioniert der Login über den Adapter nicht mehr.

```
2021-03-30 07:55:33.096 - info: host.rpi4htr stopInstance system.adapter.vw-connect.0 (force=false, process=true)
--
2021-03-30 07:55:33.102 - info: host.rpi4htr stopInstance system.adapter.vw-connect.0 send kill signal
2021-03-30 07:55:33.103 - info: vw-connect.0 (23431) Got terminate signal TERMINATE_YOURSELF
2021-03-30 07:55:33.105 - info: vw-connect.0 (23431) cleaned everything up...
2021-03-30 07:55:33.107 - info: vw-connect.0 (23431) terminating
2021-03-30 07:55:33.109 - info: vw-connect.0 (23431) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2021-03-30 07:55:33.821 - info: host.rpi4htr instance system.adapter.vw-connect.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2021-03-30 07:55:36.315 - info: host.rpi4htr instance system.adapter.vw-connect.0 started with pid 23757
2021-03-30 07:55:40.301 - info: vw-connect.0 (23757) Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system
2021-03-30 07:55:40.367 - info: vw-connect.0 (23757) starting. Version 0.0.30 in /opt/iobroker/node_modules/iobroker.vw-connect, node: v10.23.3, js-controller: 3.2.16
2021-03-30 07:55:42.973 - error: vw-connect.0 (23757) Login was not successful, please check your login credentials and selected type
2021-03-30 07:55:42.974 - error: vw-connect.0 (23757) TypeError: Cannot read property 'split' of undefined
2021-03-30 07:55:42.978 - error: vw-connect.0 (23757) TypeError: Cannot read property 'split' of undefined
at Request.request.post [as _callback] (/opt/iobroker/node_modules/iobroker.vw-connect/main.js:469:105)
at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
at Request.emit (events.js:198:13)
at Request. (/opt/iobroker/node_modules/request/request.js:1154:10)
at Request.emit (events.js:198:13)
at IncomingMessage. (/opt/iobroker/node_modules/request/request.js:1076:12)
at Object.onceWrapper (events.js:286:20)
at IncomingMessage.emit (events.js:203:15)
at endReadableNT (_stream_readable.js:1145:12)
at process._tickCallback (internal/process/next_tick.js:63:19)
2021-03-30 07:55:42.979 - error: vw-connect.0 (23757) Login Failed


```

**Comment by TobiasSt78** [comment]
Erledigt: Löschen aller Datenpunkte unter Objekte hat das Problem behoben.
